name: credio_reader
description: A new Flutter plugin project.
version: 0.0.1
homepage:

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=2.15.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  pin_code_fields: ^8.0.1
  permission_handler: ^9.2.0
  screenshot: ^2.3.0
  modal_bottom_sheet: ^3.0.0
  intl: ^0.19.0
  provider: ^6.1.2
  flutter_plugin_qpos: ^0.1.4+2-debug
  dio: ^5.6.0
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


# The following section is specific to Flutter packages.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' specifies the class (in Java, Kotlin, Swift, Objective-C, etc.)
  # which should be registered in the plugin registry. This is required for
  # using method channels.
  # The Android 'package' specifies package in which the registered class is.
  # This is required for using method channels on Android.
  # The 'ffiPlugin' specifies that native code should be built and bundled.
  # This is required for using `dart:ffi`.
  # All these are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: com.crediometer.credio_reader
        pluginClass: CredioReaderPlugin
      ios:
        pluginClass: CredioReaderPlugin

  # To add assets to your plugin package, add an assets section, like this:
  assets:
    - images/
    - .env
  